apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-retriever
  namespace: atharva-ml
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: atharva-retriever
  updatePolicy:
    updateMode: "Off"
