# Enable ImageVolume feature gate (beta, disabled-by-default as of v1.33+)
# Ref: "Use an Image Volume With a Pod" + Feature Gates docs.
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta3
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        feature-gates: "ImageVolume=true"
    controllerManager:
      extraArgs:
        feature-gates: "ImageVolume=true"
    scheduler:
      extraArgs:
        feature-gates: "ImageVolume=true"
  - |
    apiVersion: kubelet.config.k8s.io/v1beta1
    kind: KubeletConfiguration
    featureGates:
      ImageVolume: true

# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: llmops-kind
nodes:
- role: control-plane
  image: kindest/node:v1.34.0
  extraMounts:
    - hostPath: /Users/gshah/work/llmops/code/test/project
      containerPath: /mnt/project
  extraPortMappings:
  - containerPort: 32000
    hostPort: 32000
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 32100
    hostPort: 32100
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 30000
    hostPort: 30000
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 30055
    hostPort: 30055
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 30056
    hostPort: 30056
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 30100
    hostPort: 30100
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 30200
    hostPort: 30200
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 30300
    hostPort: 30300
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 30400
    hostPort: 30400
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 30500
    hostPort: 30500
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 30600
    hostPort: 30600
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 30700
    hostPort: 30700
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 30800
    hostPort: 30800
    listenAddress: "0.0.0.0"
    protocol: tcp
- role: worker
  image: kindest/node:v1.34.0
  extraMounts:
    - hostPath: /Users/gshah/work/llmops/code/test/project
      containerPath: /mnt/project
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 8000
    hostPort: 8000
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 8001
    hostPort: 8001
    listenAddress: "0.0.0.0"
    protocol: tcp

- role: worker
  image: kindest/node:v1.34.0
  extraMounts:
    - hostPath: /Users/gshah/work/llmops/code/test/project
      containerPath: /mnt/project
