apiVersion: v1
kind: Service
metadata:
  name: atharva-retriever
  namespace: atharva-ml
  labels:
    app: retriever
spec:
  type: NodePort
  selector: { app: retriever }
  ports:
  - name: http
    port: 8001
    targetPort: 8001
    nodePort: 30100
